import { openSans } from './fonts'

import './globals.scss'

export const metadata = {
  title: 'Markdown',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>{children}</body>
    </html>
  )
}
